//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/CollectMsg.proto
namespace proto.CollectMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3Info")]
  public partial class Vector3Info : global::ProtoBuf.IExtensible
  {
    public Vector3Info() {}
    
    private int _sensorDataType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sensorDataType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sensorDataType
    {
      get { return _sensorDataType; }
      set { _sensorDataType = value; }
    }
    private int _nodeType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nodeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nodeType
    {
      get { return _nodeType; }
      set { _nodeType = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTranRoPo")]
  public partial class MsgTranRoPo : global::ProtoBuf.IExtensible
  {
    public MsgTranRoPo() {}
    
    private readonly global::System.Collections.Generic.List<Vector3Info> _unityRoPoList = new global::System.Collections.Generic.List<Vector3Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"unityRoPoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Vector3Info> unityRoPoList
    {
      get { return _unityRoPoList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUploadVector")]
  public partial class MsgUploadVector : global::ProtoBuf.IExtensible
  {
    public MsgUploadVector() {}
    
    private readonly global::System.Collections.Generic.List<Vector3Info> _vector3InfoList = new global::System.Collections.Generic.List<Vector3Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"vector3InfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Vector3Info> vector3InfoList
    {
      get { return _vector3InfoList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTimeUpByUser")]
  public partial class MsgTimeUpByUser : global::ProtoBuf.IExtensible
  {
    public MsgTimeUpByUser() {}
    
    private string _userid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}